### ISSUE TITLE
关于在mac m1上无法使用的问题

### ISSUE THREAD

**Issue by kukudechen-chen** [Orange-Cyberdefense/arsenal#19]
您好，感谢您的这个伟大的项目！

操作系统版本：
macOS Big Sur ：
版本：11.2.3 (20D91)  Apple M1 
问题： 在mac上无法运行
<img width="1009" alt="截屏2021-09-16 上午1 43 53" src="https://user-images.githubusercontent.com/70738932/133483185-4417e9c3-31ba-4f2c-9d09-1fa225f18241.png">

apple@xiaoxiong arsenal-master % ./run 
Traceback (most recent call last):
  File "/Users/apple/Downloads/arsenal-master/arsenal/modules/gui.py", line 39, in draw_prompt
    promptwin.addstr("☠️  >", curses.color_pair(Gui.BASIC_COLOR))
_curses.error: addwstr() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./arsenal/app.py", line 179, in <module>
    App().run()
  File "./arsenal/app.py", line 66, in run
    self.start(args, cheatsheets)
  File "./arsenal/app.py", line 73, in start
    cmd = gui.run(cheatsheets)
  File "/Users/apple/Downloads/arsenal-master/arsenal/modules/gui.py", line 814, in run
    wrapper(self.cheats_menu.run)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/apple/Downloads/arsenal-master/arsenal/modules/gui.py", line 307, in run
    self.draw(stdscr)
  File "/Users/apple/Downloads/arsenal-master/arsenal/modules/gui.py", line 225, in draw
    self.draw_prompt()
  File "/Users/apple/Downloads/arsenal-master/arsenal/modules/gui.py", line 41, in draw_prompt
    promptwin.addstr(">>>>", curses.color_pair(Gui.BASIC_COLOR))
_curses.error: addwstr() returned ERR

**Comment by milesgratz** [comment]
Seems similar to #8 (drawing of the ☠️ character)

**Comment by dc-avasilev** [comment]
![arsenal_–_gui_py](https://user-images.githubusercontent.com/17141669/134539076-17b3a206-1061-43fb-a43b-ae3cda2e6d4b.png)
it's helped me

**Comment by Mayfly277** [comment]
I thought the try catch i added in the code solved the problem. Obviously not :(
I will investigate, but during this time, as a work around you could delete the skull and put others chars instead like @dc-avasilev  done in his comment.

**Comment by dc-avasilev** [comment]
try this char
![Снимок экрана 2021-09-27 в 15 06 04](https://user-images.githubusercontent.com/17141669/134904833-9d1730f2-e8fe-4129-81d7-cd19debb0783.png)
![Снимок экрана 2021-09-27 в 15 05 31](https://user-images.githubusercontent.com/17141669/134904842-9c86cc76-035e-4cb3-a951-95c0003bdccf.png)

**Comment by v1k1ngfr** [comment]
Hi @kukudechen-chen,

Is the workaround from @dc-avasilev working for you ?
