### ISSUE TITLE
Cannot run any tool (permission denied)

### ISSUE THREAD

**Issue by theoneandonly-vector** [Orange-Cyberdefense/arsenal#46]
Example:
```
??(root?localhost)-[~]
??# arsenal
Traceback (most recent call last):
  File "/usr/local/bin/arsenal", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/arsenal/app.py", line 185, in main
    App().run()
  File "/usr/local/lib/python3.10/dist-packages/arsenal/app.py", line 64, in run
    self.start(args, cheatsheets)
  File "/usr/local/lib/python3.10/dist-packages/arsenal/app.py", line 161, in start
    self.prefil_shell_cmd(cmd)
  File "/usr/local/lib/python3.10/dist-packages/arsenal/app.py", line 178, in prefil_shell_cmd
    fcntl.ioctl(stdin, termios.TIOCSTI, c)
PermissionError: [Errno 13] Permission denied
```

**Comment by Mayfly277** [comment]
can you give me your os and the way you install arsenal so i can reproduce the issue ?

**Comment by theoneandonly-vector** [comment]
Kali  for ARM64 started in Termux using root-permissions.

**Comment by v1k1ngfr** [comment]
Hello,
Arsenal is not validated on ARM64 yet.
We will try to do it in future release.

**Comment by Guilhem7** [comment]
Hi, your issue is related to this one: https://github.com/Orange-Cyberdefense/arsenal/issues/61 and the PR associated !
