### ISSUE TITLE
TIOCSTI disabled by default in recent kernels breaks arsenal

### ISSUE THREAD

**Issue by xAiluros** [Orange-Cyberdefense/arsenal#61]
It seems recent kernels are disabling TIOCSTI by default. This results in the following error and arsenal being unusable:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/[...]/arsenal/arsenal/__main__.py", line 14, in <module>
    main()
  File "[...]/arsenal/app.py", line 185, in main
    App().run()
  File "[...]l/arsenal/app.py", line 64, in run
    self.start(args, cheatsheets)
  File "[...]/arsenal/app.py", line 161, in start
    self.prefil_shell_cmd(cmd)
  File "[...]/arsenal/app.py", line 178, in prefil_shell_cmd
    fcntl.ioctl(stdin, termios.TIOCSTI, c)
OSError: [Errno 5] Input/output error
```

This was on Kali after recent update, kernel: 6.3.0-kali1-amd64  SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux
But on Arch I think it's been a problem for longer.

For now it can be fixed with: `sysctl -w dev.tty.legacy_tiocsti=1`

But I think it's being disabled due to security issues. So I think arsenal should stop using it if possible. Not sure about alternative though.

**Comment by v1k1ngfr** [comment]
Hello @xAiluros,
Thanks for this information. We will fix this point during code review.

**Comment by kib3rvo1n** [comment]
permanent fix:

1. run: sudo nano /etc/sysctl.conf
2. paste: dev.tty.legacy_tiocsti=1
3. Save
4. run: sudo sysctl -p
