### ISSUE TITLE
Character "|" in constant not supported

### ISSUE THREAD

**Issue by claire-lex** [Orange-Cyberdefense/arsenal#7]
Whenever there is a `|` in a command's variable part `<variable>` (silly idea, isn't it? :)), the program's GUI part crashes with a `IndexError: list index out of range`.

**Example:**

Input:

```
hashcat hashfile -r <rule|best64.rule> <dict|wordlist.txt>
```

Output:

```
Traceback (most recent call last):
  File "./arsenal/app.py", line 174, in <module>
    App().run()
  File "./arsenal/app.py", line 68, in run
    cmd = gui.run(cheatsheets)
  File "path/arsenal/arsenal/modules/gui.py", line 704, in run
    wrapper(self.cheats_menu.run)
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "path/arsenal/arsenal/modules/gui.py", line 301, in run
    wrapper(args_menu.run)
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "path/arsenal/arsenal/modules/gui.py", line 597, in run
    self.draw(stdscr)
  File "path/arsenal/arsenal/modules/gui.py", line 571, in draw
    self.draw_args_preview()
  File "path/arsenal/arsenal/modules/gui.py", line 540, in draw_args_preview
    if Gui.cmd.args[(i-1)//2][1] == "":
IndexError: list index out of range

```

**Comment by claire-lex** [comment]
The problem is related to the size of arguments with format `<name|default_value>` which may be too long for the GUI part. This bug is not fixed (requires another issue), however the `<name|default_value>` format is supported from commit `67656ff` on branch develop.

Usage example:
```
sudo tcpreplay -i <iface|enp0s31f6> -l 1 <outfile|stream.pcap>
```
