### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by arddluma** [Orange-Cyberdefense/arsenal#8]
Hi, Thank you for this great project!

**OS Version:**
**macOS Big Sur :
Version: 11.0.1 (20B29)**
**Issue:**
Running Arsenal Script with python3 on MacOs Big Sur is leading to the down mentioned error, it seems something like GUI Error!
**Output:**
![image](https://user-images.githubusercontent.com/34317628/103292666-95405f00-49ee-11eb-9f86-faf3d689fbbf.png)

`meridian0x01@Meridians-MacBook-Pro arsenal (master) $ ./run 
Traceback (most recent call last):
  File "./arsenal/app.py", line 140, in <module>
    App().run()
  File "./arsenal/app.py", line 59, in run
    cmd = gui.Gui().run(cheatsheets)
  File "/Users/meridian0x01/Desktop/workspace/Tools/arsenal/arsenal/modules/gui.py", line 700, in run
    wrapper(cheats_menu.run)
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/curses/init.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/meridian0x01/Desktop/workspace/Tools/arsenal/arsenal/modules/gui.py", line 289, in run
    self.draw(stdscr)
  File "/Users/meridian0x01/Desktop/workspace/Tools/arsenal/arsenal/modules/gui.py", line 203, in draw
    self.draw_prompt()
  File "/Users/meridian0x01/Desktop/workspace/Tools/arsenal/arsenal/modules/gui.py", line 36, in draw_prompt
    promptwin.addstr(":skull_crossbones:  >", curses.color_pair(Gui.BASIC_COLOR))
_curses.error: addwstr() returned ERR`

Any solution?

**Comment by Mayfly277** [comment]
Hello, thanks for the issue. I didn't test on macOS (i will try to find one to reproduce the issue)
Seems you got an error on the prompt drawing (I think the error come from the draw of the fancy skull character)
Could you please try to change the prompt character in this file : https://github.com/Orange-Cyberdefense/arsenal/blob/master/arsenal/modules/gui.py#L36 and tell me if it solve the problem ?
regards.

**Comment by arddluma** [comment]
Thank you so much ! The issue is now resolved.

**Comment by junmoxiao** [comment]
The issue is now resolved.Thank you so much!
Can you merge the modification?

**Comment by Mayfly277** [comment]
Hi @arddluma, can you give a try on the develop or cheat_sheet_improvements branchs to see if the issue is resolved ?

**Comment by Mayfly277** [comment]
Should be resolved now. if you still got issues, please reopen :)
