### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Tripse** [Orange-Cyberdefense/arsenal#88]
Traceback (most recent call last):
  File "/opt/homebrew/bin/arsenal", line 5, in <module>
    from arsenal.app import main
  File "/opt/homebrew/lib/python3.12/site-packages/arsenal/app.py", line 13, in <module>
    from .modules import cheat
  File "/opt/homebrew/lib/python3.12/site-packages/arsenal/modules/cheat.py", line 9, in <module>
    from yaml import load as yml_load, FullLoader
ModuleNotFoundError: No module named 'yaml'

**Comment by Tripse** [comment]
Emmm.. sorry , installing again can resolve the error
pip3.12 install  arsenal-cli --break-system-packages
