### ISSUE TITLE
20240521- powershell.md's issue

### ISSUE THREAD

**Issue by AZIZI-Sajjad** [Orange-Cyberdefense/arsenal#89]
Hi Guys,

There is a broblem with "arsenal/arsenal/data/cheats/Windows/powershell.md" commande : 

## powershell - Verify application whitelisting
```
Get-ChildItem -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\SrpV2\Exe
```

It makes the following error, and the application arsenal fails :

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/etc/arsenal/arsenal/__main__.py", line 14, in <module>
    main()
  File "/etc/arsenal/arsenal/app.py", line 185, in main
    App().run()
  File "/etc/arsenal/arsenal/app.py", line 58, in run
    cheatsheets = cheat.Cheats().read_files(config.CHEATS_PATHS, config.FORMATS,
  File "/etc/arsenal/arsenal/modules/cheat.py", line 445, in read_files
    parsers[file_format](str(entry.absolute()))
  File "/etc/arsenal/arsenal/modules/cheat.py", line 298, in parse_markdown
    with open(filename) as f:
OSError: [Errno 22] Invalid argument: '/etc/arsenal/arsenal/data/cheats/Windows/powershell-bkp.md'

**Comment by Guilhem7** [comment]
Hi,

I am unable to reproduce this issue on my computer. Can you give me more details.
I tried on ubuntu with arsenal version:
```bash
./run --version
arsenal (version 1.2.1)

python3 --version
Python 3.8.10
```
What is your version of **arsenal** ? Do you still have this issue ?

Moreover it seems that the cheat which trigger the error does not exists _powershell-bkp.md_.

Regards

**Comment by v1k1ngfr** [comment]
Hello,
The file powershell-bkp.md is not included in Arsenal, you should have a look at it because it's the root cause of your error.

Have a nice day
